imports = ["postgres.nix"]

[services.postgres]
package = "pkgs.postgresql_15"
setupPostgresOnStartup = true
listenAddresses = "*"

[[env]]
name = "DBNAME"
value = "st"

[[env]]
name = "PGPORT"
value = "9091"

[[env]]
name = "PGUSER"
eval = "${USER:-$(id -nu)}"

[[env]]
name = "ST_DATABASE_URL"
eval = 'postgres:///$DBNAME?port=$PGPORT\&host=$PGHOST'

[[env]]
name = "ST_DATABASE_URL_LOCALHOST"
eval = 'postgres://$PGUSER@localhost:$PGPORT/$DBNAME'

[[env]]
name = "ST_DATABASE_JDBC_URL"
eval = 'jdbc:postgresql://localhost:$PGPORT/$DBNAME'

[[env]]
name = "ST_DATABASE_MIGRATION_DIR"
eval = '$PRJ_ROOT/backend/src/main/resources/db'

[[env]]
name = "ST_DATABASE_MIGRATION_MOCK_DIR"
eval = '$PRJ_ROOT/backend/src/main/resources/mockdata/db'

[[commands]]
name = "setup-db"
command = '''
createdb  -h $PGDATA -p $PGPORT $DBNAME
          '''

[[commands]]
name = "reset-db"
command = '''
rm -rf $PGDATA
setup-postgres
postgres
          '''