[[env]]
name = "ST_FRONTEND"
eval = "$PRJ_ROOT/frontend/dist"

[[env]]
name = "ST_SERVER_PORT"
value = "9090"

[[env]]
name = "ST_INVIDIOUS_ROOT_URL"
value = "https://invidious.nerdvpn.de"

[serviceGroups.svr]
description = "server and database"
[serviceGroups.svr.services.server]
command = "mill backend.run"
[serviceGroups.svr.services.database]
command = "postgres"

